# Generated by Django 4.2.2 on 2023-08-02 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_addingproducttable'),
    ]

    operations = [
        migrations.CreateModel(
            name='addingproducttable1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('productname', models.CharField(max_length=200)),
                ('productprice', models.CharField(max_length=200)),
                ('productcatagory', models.CharField(max_length=200)),
                ('productdescription', models.CharField(max_length=200)),
                ('productimage', models.ImageField(upload_to='productimage/')),
                ('productsize', models.CharField(max_length=200)),
            ],
        ),
        migrations.DeleteModel(
            name='addingproducttable',
        ),
    ]
