# Generated by Django 4.2.2 on 2023-08-02 05:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_addingproducttable1_delete_addingproducttable'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='addingproducttable1',
            new_name='addingproducttable',
        ),
    ]
