# Generated by Django 4.2.2 on 2023-08-03 04:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_rename_addingproducttable1_addingproducttable'),
    ]

    operations = [
        migrations.CreateModel(
            name='carttable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.CharField(max_length=200)),
                ('total', models.CharField(max_length=200)),
                ('status', models.CharField(default='pending', max_length=200)),
                ('items_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.addingproducttable')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.signintable')),
            ],
        ),
    ]
