# Generated by Django 4.2.2 on 2023-08-11 04:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_alter_carttable_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carttable',
            name='total',
            field=models.FloatField(max_length=200),
        ),
    ]
